//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTestWcf.WcfStrvTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientesDTO", Namespace="http://schemas.datacontract.org/2004/07/TestWcfService.DTO")]
    [System.SerializableAttribute()]
    public partial class ClientesDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodClienteNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodClienteN {
            get {
                return this.CodClienteNField;
            }
            set {
                if ((this.CodClienteNField.Equals(value) != true)) {
                    this.CodClienteNField = value;
                    this.RaisePropertyChanged("CodClienteN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCliente {
            get {
                return this.NomClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomClienteField, value) != true)) {
                    this.NomClienteField = value;
                    this.RaisePropertyChanged("NomCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfStrvTest.IMyWcfServiceTest")]
    public interface IMyWcfServiceTest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWcfServiceTest/Add", ReplyAction="http://tempuri.org/IMyWcfServiceTest/AddResponse")]
        void Add(WinTestWcf.WcfStrvTest.ClientesDTO cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWcfServiceTest/Add", ReplyAction="http://tempuri.org/IMyWcfServiceTest/AddResponse")]
        System.Threading.Tasks.Task AddAsync(WinTestWcf.WcfStrvTest.ClientesDTO cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWcfServiceTest/GetList", ReplyAction="http://tempuri.org/IMyWcfServiceTest/GetListResponse")]
        WinTestWcf.WcfStrvTest.ClientesDTO[] GetList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWcfServiceTest/GetList", ReplyAction="http://tempuri.org/IMyWcfServiceTest/GetListResponse")]
        System.Threading.Tasks.Task<WinTestWcf.WcfStrvTest.ClientesDTO[]> GetListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyWcfServiceTestChannel : WinTestWcf.WcfStrvTest.IMyWcfServiceTest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWcfServiceTestClient : System.ServiceModel.ClientBase<WinTestWcf.WcfStrvTest.IMyWcfServiceTest>, WinTestWcf.WcfStrvTest.IMyWcfServiceTest {
        
        public MyWcfServiceTestClient() {
        }
        
        public MyWcfServiceTestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWcfServiceTestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWcfServiceTestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWcfServiceTestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(WinTestWcf.WcfStrvTest.ClientesDTO cliente) {
            base.Channel.Add(cliente);
        }
        
        public System.Threading.Tasks.Task AddAsync(WinTestWcf.WcfStrvTest.ClientesDTO cliente) {
            return base.Channel.AddAsync(cliente);
        }
        
        public WinTestWcf.WcfStrvTest.ClientesDTO[] GetList() {
            return base.Channel.GetList();
        }
        
        public System.Threading.Tasks.Task<WinTestWcf.WcfStrvTest.ClientesDTO[]> GetListAsync() {
            return base.Channel.GetListAsync();
        }
    }
}
